name: Build the Parachain Implementers's Guide and save as static website.

on:
  schedule:
    - cron: "0 * * * *"
  push:
    paths:
    - '.github/workflows/implementers_guide.yml'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout local repo
      uses: actions/checkout@v2

    - name: Clone polkadot repo
      uses: actions/checkout@v2
      with:
        repository: paritytech/polkadot
        path: .tmp_polkadot

    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: 'latest'

    - name: Setup mdbook-linkcheck
      run: |
        curl -LSfs https://japaric.github.io/trust/install.sh | \
        sh -s -- --git Michael-F-Bryan/mdbook-linkcheck

    - name: Use Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Setup mdbook-graphviz
      run: |
        sudo apt install -y graphviz
        cargo install mdbook-graphviz

    - name: Setup mdbook-mermaid
      run: |
        cargo install mdbook-mermaid

    - name: Build book.
      run: |
        mdbook build .tmp_polkadot/roadmap/implementers-guide/

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .tmp_polkadot/roadmap/implementers-guide/book/html/

