name: Build the Parachain Implementers's Guide and save as static website.

on:
  schedule:
    - cron: "0 * * * *"
  push:
    paths:
    - '.github/workflows/implementers_guide.yml'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout local repo
      uses: actions/checkout@v2

    - name: Clone polkadot repo
      uses: actions/checkout@v2
      with:
        repository: paritytech/polkadot
        path: .tmp_polkadot

    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: 'latest'

    - run: |
        mdbook build .tmp_polkadot/roadmap/implementors-guide/

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .tmp_polkadot/roadmap/implementors-guide/book/html/

